### PR TITLE
Add version 21.5.0 as the start of the first epoch

### PR DESCRIPTION
**Pull request by merlijn-sebrechts**
Following [the hard stops builtin to sentry](https://develop.sentry.dev/self-hosted/releases/#hard-stops).

The current version is 21.2.0. We need to ensure users install 21.5.0 before going further, so I mark that version as the "transitional" release to go beyond.

### CODE REVIEW

**Comment by lucyllewy** [comment]
This will fail to build - I'm working up a re-rolled PR with the requisite fixes to get the build to complete

**Comment by merlijn-sebrechts** [comment]
@diddledani I changed `epoch: 1` to `epoch: 1*`, because we can't actually update to epoch 1 without user interaction.

This way, users can install the required dependencies, and then manually switch to epoch 1. We should probably also update the description in the store and the readme with instructions for how to upgrade, once everything is in place.

**Comment by lucyllewy** [comment]
oops, I didn't mean to set the epoch without the `*`. I guess that was while I was fiddling to ensure upgrades worked right and I forgot to revert before committing 🤦🏻‍♀️ 

Edit: oh I see what you're saying is different to how I interpreted it originally - yes, that is a good plan to *drop* the `*` from the epoch for now. Although we could add a `pre-refresh` hook to the stable branch first (maybe masked with a different epoch number that *is* upgradable automatically but ensures the `pre-refresh` hook is present before then moving onto this release) which checks that the admin/user has set a snap setting to indicate that they have done the required bits to allow the migration - i.e. got snuba et al running. Maybe `sudo snap set sentry sentry21-dependencies-are-set-up=true` (wording is hard!) - we can set this setting in an `install` hook for new installs so that they aren't gated if we forget to remove the check in newer releases.

**Review by lucyllewy — APPROVED** [review]
I think this is good-to-go then :-) Let's wait to see that the build completes and then we can merge <3

**Pull request merged**
