### PR TITLE
Fix failing i386 build due to setuptools-rust

### PR DESCRIPTION
**Pull request by lucyllewy**
* Snapcraft doesn't download `setuptools-rust` during pull, so it isn't available when building. So, add it as an explicit dependency.

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
FYI: closed and opened to run this through the just merged action

**Comment by merlijn-sebrechts** [comment]
Hm, build on x86 seems to be failing, but it's not due to your change I think. Do you want me to merge this and fix the other issue later, or do you want to take a shot at it in this PR?

**Comment by lucyllewy** [comment]
That looks to be caused by this commit from February 18 by @joedborg (I can't find an associated PR) 4f0d7e2

**Comment by merlijn-sebrechts** [comment]
I propose to first merge https://github.com/snapcrafters/sentry/pull/48, then merge this PR and then work through the epoch PRs

**Review by merlijn-sebrechts — APPROVED** [review]
LGTM! Seems like the build is succeeding too.

**Pull request merged**
